import type { Album, Artista, Genero, Sello } from './types';

export const mockArtistas: Artista[] = [
  { id_artista: 1, nombre: 'Kraftwerk', pais: 'Germany' },
  { id_artista: 2, nombre: 'Daft Punk', pais: 'France' },
  { id_artista: 3, nombre: 'The Beatles', pais: 'UK' },
  { id_artista: 4, nombre: 'Pink Floyd', pais: 'UK' },
  { id_artista: 5, nombre: 'Various Artists' }, // For compilations
  { id_artista: 6, nombre: 'Miles Davis', pais: 'USA'},
  { id_artista: 7, nombre: 'Massive Attack', pais: 'UK'},
];

export const mockGeneros: Genero[] = [
  { id_genero: 1, nombre: 'Electronic' },
  { id_genero: 2, nombre: 'Rock' },
  { id_genero: 3, nombre: 'Pop' },
  { id_genero: 4, nombre: 'Jazz' },
  { id_genero: 5, nombre: 'Trip Hop' },
  { id_genero: 6, nombre: 'Techno' },
];

export const mockSellos: Sello[] = [
  { id_sello: 1, nombre: 'EMI' },
  { id_sello: 2, nombre: 'Virgin Records' },
  { id_sello: 3, nombre: 'Parlophone' },
  { id_sello: 4, nombre: 'Columbia' },
  { id_sello: 5, nombre: 'Warp Records' },
];

export const mockAlbums: Album[] = [
  {
    id_album: 1,
    titulo: 'Trans-Europe Express',
    sello_id: 1,
    sello_nombre: 'EMI',
    anio_lanzamiento: 1977,
    genero_id: 1,
    genero_nombre: 'Electronic',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[0]],
    canciones: [
      { id_cancion: 1, titulo: 'Europe Endless', bpm: 115, artistas: [mockArtistas[0]] },
      { id_cancion: 2, titulo: 'The Hall of Mirrors', bpm: 85, artistas: [mockArtistas[0]] },
      { id_cancion: 3, titulo: 'Showroom Dummies', bpm: 122, artistas: [mockArtistas[0]] },
    ],
  },
  {
    id_album: 2,
    titulo: 'Discovery',
    sello_id: 2,
    sello_nombre: 'Virgin Records',
    anio_lanzamiento: 2001,
    genero_id: 1,
    genero_nombre: 'Electronic',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[1]],
    canciones: [
      { id_cancion: 4, titulo: 'One More Time', bpm: 123, artistas: [mockArtistas[1]] },
      { id_cancion: 5, titulo: 'Aerodynamic', bpm: 123, artistas: [mockArtistas[1]] },
      { id_cancion: 6, titulo: 'Digital Love', bpm: 125, artistas: [mockArtistas[1]] },
    ],
  },
  {
    id_album: 3,
    titulo: 'Abbey Road',
    sello_id: 3,
    sello_nombre: 'Parlophone',
    anio_lanzamiento: 1969,
    genero_id: 2,
    genero_nombre: 'Rock',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[2]],
    canciones: [
      { id_cancion: 7, titulo: 'Come Together', bpm: 82, artistas: [mockArtistas[2]] },
      { id_cancion: 8, titulo: 'Something', bpm: 70, artistas: [mockArtistas[2]] },
      { id_cancion: 9, titulo: 'Here Comes The Sun', bpm: 129, artistas: [mockArtistas[2]] },
    ],
  },
  {
    id_album: 4,
    titulo: 'The Dark Side of the Moon',
    sello_id: 1,
    sello_nombre: 'EMI',
    anio_lanzamiento: 1973,
    genero_id: 2,
    genero_nombre: 'Rock',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[3]],
    canciones: [
      { id_cancion: 10, titulo: 'Speak to Me/Breathe', bpm: 72, artistas: [mockArtistas[3]] },
      { id_cancion: 11, titulo: 'Time', bpm: 120, artistas: [mockArtistas[3]] },
      { id_cancion: 12, titulo: 'Money', bpm: 126, artistas: [mockArtistas[3]] },
    ],
  },
  {
    id_album: 5,
    titulo: 'Kind of Blue',
    sello_id: 4,
    sello_nombre: 'Columbia',
    anio_lanzamiento: 1959,
    genero_id: 4,
    genero_nombre: 'Jazz',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[5]],
    canciones: [
      { id_cancion: 13, titulo: 'So What', bpm: 135, artistas: [mockArtistas[5]] },
      { id_cancion: 14, titulo: 'Freddie Freeloader', bpm: 95, artistas: [mockArtistas[5]] },
      { id_cancion: 15, titulo: 'Blue in Green', bpm: 75, artistas: [mockArtistas[5]] },
    ],
  },
  {
    id_album: 6,
    titulo: 'Mezzanine',
    sello_id: 2,
    sello_nombre: 'Virgin Records',
    anio_lanzamiento: 1998,
    genero_id: 5,
    genero_nombre: 'Trip Hop',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: false,
    artistas: [mockArtistas[6]],
    canciones: [
      { id_cancion: 16, titulo: 'Angel', bpm: 80, artistas: [mockArtistas[6]] },
      { id_cancion: 17, titulo: 'Teardrop', bpm: 78, artistas: [mockArtistas[6]] },
      { id_cancion: 18, titulo: 'Inertia Creeps', bpm: 98, artistas: [mockArtistas[6]] },
    ],
  },
  {
    id_album: 7,
    titulo: 'Techno Compilation Vol. 1',
    sello_id: 5,
    sello_nombre: 'Warp Records',
    anio_lanzamiento: 2023,
    genero_id: 6,
    genero_nombre: 'Techno',
    url_caratula: 'https://placehold.co/300x300.png',
    formato: 'LP',
    es_compilacion: true,
    artistas: [mockArtistas[4]], // "Various Artists"
    canciones: [
      { id_cancion: 19, titulo: 'Future Beat', bpm: 130, artista_principal_nombre: 'DJ Electron' },
      { id_cancion: 20, titulo: 'Acid Dreams', bpm: 135, artista_principal_nombre: 'Syntax Error' },
      { id_cancion: 21, titulo: 'Rhythm Machine', bpm: 128, artista_principal_nombre: 'The Modulator' },
    ],
  },
];
